#         _               _
#    __ _| |__   ___  ___| |_
#   / _` | '_ \ / _ \/ __| __/
#  | (_| | | | | (_) \__ \ |_
#   \__, |_|_|_|\___/|___/\__|
#   |___/      /   _ \
#          (¯\| o (@) |/¯)
#           \_  .___.  _/
#            /   !_!   \
#           /_.--._.--._\

version: "3"

services:
  transmission:
    image: ghostserverd/transmission-combustion
    container_name: transmission
    restart: always
    ports:
      - "${TRANS_WEBUI_PORT}:${TRANS_WEBUI_PORT}"
      - "${TRANS_CONNECTION_PORT}:${TRANS_CONNECTION_PORT}"
      - "${TRANS_CONNECTION_PORT}:${TRANS_CONNECTION_PORT}/udp"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TRANS_WEBUI_USER=${TRANS_WEBUI_USER}
      - TRANS_WEBUI_PASS=${TRANS_WEBUI_PASS}
      - TRANS_MAX_RETENTION=${TRANS_MAX_RETENTION}
      - TRANS_MAX_RATIO=${TRANS_MAX_RATIO}
      - TRANS_CONNECTION_PORT=${TRANS_CONNECTION_PORT}
      - FILEBOT_PORT=${FILEBOT_PORT}
      - TZ=America/Los_Angeles
    volumes:
      - ${CONFIG_DIR}/transmission:/config
      - ${DOWNLOAD_DIR}:/downloads
      - ${MEDIA_DIR}:/media

  filebot:
    image: ghostserverd/filebot
    container_name: filebot
    restart: always
    ports:
      - "7676:7676"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Los_Angeles
      - FILEBOT_PORT=${FILEBOT_PORT}
    volumes:
      - ${CONFIG_DIR}/filebot:/config
      - ${DOWNLOAD_DIR}:/downloads
      - ${MEDIA_DIR}:/media

  sonarr:
    image: ghostserverd/sonarr
    container_name: sonarr
    restart: always
    ports:
      - "8989:8989"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Los_Angeles
    volumes:
      - ${CONFIG_DIR}/sonarr:/config
      - ${DOWNLOAD_DIR}:/data/completed/tv/
      - ${TV_DIR}:/tv

  radarr:
    image: ghostserverd/radarr
    container_name: radarr
    restart: always
    ports:
      - "7878:7878"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Los_Angeles
    volumes:
      - ${CONFIG_DIR}/radarr:/config
      - ${DOWNLOAD_DIR}:/data/completed/movies/
      - ${MOVIES_DIR}:/movies

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    restart: always
    ports:
      - "6767:6767"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Los_Angeles
    volumes:
      - ${CONFIG_DIR}/bazarr:/config
      - ${TV_DIR}:/tv
      - ${MOVIES_DIR}:/movies

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: always
    ports:
      - "9117:9117"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Los_Angeles
      - JACKETT_KEY=0000
    volumes:
      - ${CONFIG_DIR}/jackett:/config
      - ${CONFIG_DIR}/jackett/downloads:/downloads

  plex:
    image: ghostserverd/plex
    container_name: plex
    restart: always
    ports:
      - "32400:32400"
      - "1900:1900"
      - "3005:3005"
      - "5353:5353"
      - "8324:8324"
      - "32410:32410"
      - "32412:32412"
      - "32413:32413"
      - "32414:32414"
      - "32469:32469"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Los_Angeles
      - VERSION=latest
    volumes:
      - ${CONFIG_DIR}/plex:/config
      - ${MEDIA_DIR}:/data
    devices:
      - "/dev/dri/card0:/dev/dri/card0"
      - "/dev/dri/renderD128:/dev/dri/renderD128"

  acestream:
    image: ikatson/aceproxy
    container_name: acestream
    restart: always
    ports:
      - "9191:8000"

  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    command: --cleanup
    restart: always
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
