# docker system prune --all --force --volumes
# https://www.filebot.net/purchase.html

version: "2"

services:
  qbittorrent:
    image: ghostserver/qbittorrent-filebot
    container_name: qbittorrent
    restart: always
    ports:
      - "6881:6881"
      - "6881:6881/udp"
      - "8080:8080"
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Los_Angeles
    volumes:
      - ${CONFIG_DIR}/qbittorrent:/config
      - ${DOWNLOAD_DIR}:/downloads
      - ${MEDIA_DIR}:/media

  sonarr:
    image: ghostserver/sonarr
    container_name: sonarr
    restart: always
    ports:
      - "8989:8989"
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Los_Angeles
    volumes:
      - ${CONFIG_DIR}/sonarr:/config
      - ${DOWNLOAD_DIR}:/data/completed/tv/
      - ${TV_DIR}:/tv

  radarr:
    image: ghostserver/radarr
    container_name: radarr
    restart: always
    ports:
      - "7878:7878"
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Los_Angeles
    volumes:
      - ${CONFIG_DIR}/radarr:/config
      - ${DOWNLOAD_DIR}:/data/completed/movies/
      - ${MOVIES_DIR}:/movies

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: always
    ports:
      - "9117:9117"
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Los_Angeles
      - JACKETT_KEY=9818
    volumes:
      - ${CONFIG_DIR}/jackett:/config
      - ${CONFIG_DIR}/jackett/downloads:/downloads

  plex:
    image: ghostserver/plex
    container_name: plex
    restart: always
    ports:
      - "32400:32400"
      - "1900:1900"
      - "3005:3005"
      - "5353:5353"
      - "8324:8324"
      - "32410:32410"
      - "32412:32412"
      - "32413:32413"
      - "32414:32414"
      - "32469:32469"
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Los_Angeles
    volumes:
      - ${CONFIG_DIR}/plex:/config
      - ${MEDIA_DIR}:/data
